#!/usr/bin/env python
import socket
import struct

FC_IP = '127.0.0.1'
FC_LISTEN_PORT = 36000
LAUNCH_FROM_PORT = 35004

LAUNCH_MESSAGE = struct.Struct("b").pack(0)

sock = socket.socket(socket.AF_INET,
                     socket.SOCK_DGRAM)
sock.bind(('0.0.0.0', LAUNCH_FROM_PORT))
sock.sendto(LAUNCH_MESSAGE, (FC_IP, FC_LISTEN_PORT))
sock.close()

print "Sending launch message"
