#!/usr/bin/env python
import socket

TCP_IP = '127.0.0.1'
TCP_PORT = 35666

ARM_MESSAGE = "#YOLO"

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((TCP_IP, TCP_PORT))
s.send(ARM_MESSAGE)
s.close()

print "Sending arming message"
