#!/usr/bin/env python
import socket

FC_IP = '127.0.0.1'
FC_LISTEN_PORT = 36000
SERVO_FROM_PORT = 35667

SERVO_MESSAGE = "ENABLE"

sock = socket.socket(socket.AF_INET,
                     socket.SOCK_DGRAM)
sock.bind(('0.0.0.0', SERVO_FROM_PORT))
sock.sendto(SERVO_MESSAGE, (FC_IP, FC_LISTEN_PORT))
sock.close()

print "Sending enable servo message"
